# Generated by Django 2.0.5 on 2018-05-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='user',
        ),
    ]
